-- MySQL Script generated by MySQL Workbench
-- Fri Oct 25 17:38:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema waa_lembrai
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `waa_lembrai` ;

-- -----------------------------------------------------
-- Schema waa_lembrai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waa_lembrai` DEFAULT CHARACTER SET utf8 ;
USE `waa_lembrai` ;

-- -----------------------------------------------------
-- Table `waa_lembrai`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `waa_lembrai`.`usuario` ;

CREATE TABLE IF NOT EXISTS `waa_lembrai`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `idade` INT(3) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
